FROM tarpha/ubuntu:openjdk-8-pi
ENV  LC_ALL=C.UTF-8
COPY run_pi.sh /run.sh
COPY kill.sh /kill.sh
RUN apt-get install -y git
RUN git clone https://github.com/tarpha/torrssen2.git
VOLUME [ "/root/data" ]
EXPOSE 8080
#ENV BASE_URL http://localhost:8080
#CMD [ "java", "-jar", "torrssen2.jar"]
ENTRYPOINT ["/run.sh"]