name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Image
      run: docker buildx build --platform linux/amd64,linux/arm64 -t tarpha/torrssen2:latest --push .
        
  #  - name: Build and push
  #    id: docker_build
  #    uses: docker/build-push-action@v2
  #    with:
  #      push: true
  #      tags: tarpha/torrssen2:latest
